version: '3.8'
services:
  fileserver:
    build: .
    image: fileserver:latest
    container_name: fileserver-container
    restart: unless-stopped
    environment:
      - PROTOCOL=${PROTOCOL:-http}
    ports:
      - "3090:3090"
      - "3091:3091"
    volumes:
      - ./files:/app/files
